from enum import Enum


class QuestDbDeploymentStatus(Enum):
    CREATION_SCHEDULED = "CREATION_SCHEDULED"
    CREATION_PENDING = "CREATION_PENDING"
    RUNNING = "RUNNING"
    UPDATE_PENDING = "UPDATE_PENDING"
    DEPLOYMENT_FAILED = "DEPLOYMENT_FAILED"
    ERROR = "ERROR"
    DELETION_SCHEDULED = "DELETION_SCHEDULED"
    DELETION_PENDING = "DELETION_PENDING"
    DELETED = "DELETED"
